title: Adversary Simulation
description: >-
  Red Teamer & Security Researcher.
baseurl: "/blogs"
url: "https://rajchowdhury240.github.io"

# Build settings
markdown: kramdown
theme: null
permalink: /:title/
future: true

# Navigation Links
navigation:
  - title: home
    url: /
  - title: blog
    url: /blog/
  - title: about
    url: /about
  - title: linkedin

    url: https://www.linkedin.com/in/chowdhury-faizal-ahammed-b09351163/
